name: Mypy

on: [pull_request]

jobs:
 mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install mypy
      run: pip install mypy
    - name: Run mypy
      run: mypy src/
